project:
  type: website
  output-dir: docs
  
website:
  title: "VCM Methodologies"
  navbar:
    left:
      - href: car-mx.qmd
        text: CAR MX
      - href: vm0007.qmd
        text: VM0007
      - href: vm0015.qmd
        text: VM0015        
      - href: vm0047.qmd
        text: VM0047         
      - href: gsar.qmd
        text: GS A/R                    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



