project:
  type: website

website:
  title: "VCM Methodologies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: car-mx.qmd
        text: CAR MX

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



